#!/bin/bash
set -e

userConfPath="/etc/sftp-users.conf"
userConfFinalPath="/var/run/sftp-users.conf"

# Prepare rssh.conf
echo "logfacility = LOG_USER" > /etc/rssh.conf
echo "allowscp" >> /etc/rssh.conf
echo "allowsftp" >> /etc/rssh.conf
echo "allowrsync" >> /etc/rssh.conf
echo "umask = 022" >> /etc/rssh.conf
echo >> /etc/rssh.conf

function printHelp() {
    echo "Add users as command arguments, STDIN or mounted in $userConfPath"
    echo "Syntax: user:pass[:e][:uid[:gid]]..."
}

function createUser() {
    # Split param
    IFS=':' read -a param <<< $@

    # Get user and pass
    user="${param[0]}"
    pass="${param[1]}"

    # Check is password is encrypted
    if [ "${param[2]}" == "e" ]; then
        # Set encryption option for chpasswd
        chpasswdOptions="-e"
        # Get user and group id
        uid="${param[3]}"
        gid="${param[4]}"
    else
        # Get user and group id
        uid="${param[2]}"
        gid="${param[3]}"
    fi

    if [ -z "$user" ]; then
        echo "FATAL: You must at least provide a username."
        exit 1
    fi

    if $(cat /etc/passwd | cut -d: -f1 | grep -q "$user"); then
        echo "FATAL: User \"$user\" already exists."
        exit 2
    fi

    # Add default useradd options
    useraddOptions="--no-user-group --shell /usr/bin/rssh"

    # Add user id if given
    if [ -n "$uid" ]; then
        useraddOptions="$useraddOptions --non-unique --uid $uid"
    fi

    # Add group id if given
    if [ -n "$gid" ]; then
        if ! $(cat /etc/group | cut -d: -f3 | grep -q "$gid"); then
            groupadd --gid $gid $gid
        fi

        useraddOptions="$useraddOptions --gid $gid"
    fi

    useradd $useraddOptions $user
    mkdir -p /home/$user
    chown $uid:$gid /home/$user
    chmod 711 /home/$user

    # Add rssh entry
    echo "user=$user:022:100110" >> /etc/rssh.conf

    if [ -z "$pass" ]; then
        pass="$(echo `</dev/urandom tr -dc A-Za-z0-9 | head -c256`)"
        chpasswdOptions=""
    fi

    echo "$user:$pass" | chpasswd $chpasswdOptions

    # Add SSH keys to authorized_keys with valid permissions
    if [ -d /home/$user/.ssh/keys ]; then
        cat /home/$user/.ssh/keys/* >> /home/$user/.ssh/authorized_keys
        chown $user /home/$user/.ssh/authorized_keys
        chmod 600 /home/$user/.ssh/authorized_keys
    fi
}

if [[ $1 =~ ^--help$|^-h$ ]]; then
    printHelp
    exit 0
fi

# Create users only on first run
if [ ! -f "$userConfFinalPath" ]; then

    # Append mounted config to final config
    if [ -f "$userConfPath" ]; then
        cat "$userConfPath" > "$userConfFinalPath"
    fi

    # Append users from arguments to final config
    for user in "$@"; do
        echo "$user" >> "$userConfFinalPath"
    done

    # Append users from STDIN to final config
    if [ ! -t 0 ]; then
        while IFS= read -r user || [[ -n "$user" ]]; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi

    # Check that we have users in config
    if [ "$(cat "$userConfFinalPath" | wc -l)" == 0 ]; then
        echo "FATAL: No users provided!"
        printHelp
        exit 3
    fi

    # Import users from final conf file
    while IFS= read -r user || [[ -n "$user" ]]; do
        createUser "$user"
    done < "$userConfFinalPath"

    # Source custom scripts, if any
    if [ -d /etc/sftp.d ]; then
        for f in /etc/sftp.d/*; do
            [ -x "$f" ] && . "$f"
        done
        unset f
    fi
fi

exec /usr/sbin/sshd -D -e
